# WRITE A NORMAL FUNCTION WHICH RECIEVES ANOTHER FUNCTION AS AN ARGUMENT.OUTPUT THE RESULT OF THAT OTHER FUNCTION IN YOUR NORMAL FUNCTION.

def another():
    print("hello world")


def normal(function):

    return function()


normal(another)


# CALL YOUR "NORMAL" FUNCTION  BY PASSING A LAMBDA FUNCTION-WHICH PERFORMS ANY OPERATION OF YOUR CHOICE-AS AN ARGUMENT.


print(normal(lambda: 2+2))
