# 1) WRITE A NORMAL FUNCTION WHICH RECIEVES ANOTHER FUNCTION AS AN ARGUMENT.OUTPUT THE RESULT OF THAT OTHER FUNCTION IN YOUR NORMAL FUNCTION.

def normal(fn):
    print(fn(10))


# 2) CALL YOUR "NORMAL" FUNCTION  BY PASSING A LAMBDA FUNCTION-WHICH PERFORMS ANY OPERATION OF YOUR CHOICE-AS AN ARGUMENT.

normal(lambda data: data**10)


# 3) TWEAK YOUR NORMAL FUNCTION BY ALLOWING INFINITE AMOUNT OF ARGUMENTS
def NORMAL(fn, *args):
    for arg in args:
        print(fn(arg))


NORMAL(lambda data: data**10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


# 4) FORMAT THE OUTPUT OF YOUR "NORMAL" FUNCTION SUCH THAT NUMBERS LOOK NICE AND ARE CENTERED IN A 20 CHARACTER COLUMN.

def NORMAL2(fn, *args):
    for arg in args:
        print(" RESULT:{0:^20.1f}".format(fn(arg)))


NORMAL2(lambda data: data**10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
